# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('guid', models.CharField(blank=True, max_length=15, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
