# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20160402_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='userbirthday',
            field=models.DateField(auto_now=True),
        ),
    ]
