# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 03:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20160402_1115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
