# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 04:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0009_auto_20160404_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='timestamp',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
