# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CmsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('contentData', models.TextField()),
                ('controller', models.CharField(max_length=150)),
                ('view', models.CharField(max_length=150)),
            ],
        ),
    ]
