# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-02 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='title',
            field=models.CharField(default='ha', max_length=30),
            preserve_default=False,
        ),
    ]
