# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 05:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(default=datetime.datetime(2016, 4, 4, 5, 34, 41, 222771, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='blog.BlogPost'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
