# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160404_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='allow_comment',
            field=models.BooleanField(default=True),
        ),
    ]
