# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpost_allow_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='answer',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='question',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
