# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-15 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160425_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_privite',
            field=models.BooleanField(default=False),
        ),
    ]
