# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rndName', models.CharField(max_length=150)),
                ('showName', models.CharField(max_length=150)),
                ('phototype', models.CharField(choices=[('private', 'private'), ('public', 'public')], max_length=10, verbose_name='photo_type')),
            ],
        ),
    ]
