# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 14:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoes',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 28, 14, 16, 49, 254054, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
